# URls:
# Aplicación completa: http://localhost:8080
# API vía proxy: http://localhost:8080/api/todos

# Anotación: Ejercicio 12.19 realizado previamente en los anteriores ejercicios: 12.17 y 12.18.
# Checklist: todas las funcionalidades de la aplicación de tareas funcionan ✔️.
# puedes editar los archivos fuente y los cambios se reflejan al recargar la aplicación ✔️.
# el frontend debe acceder al backend a través de Nginx, por lo que las solicitudes deben hacerse a http://localhost:8080/api/todos ✔️.

services:
  todo-frontend:
    image: todo-frontend-dev
    volumes:
      - ./todo-frontend:/usr/src/app
    environment:
      # El frontend no accede directamente al backend como hacia previamente. Todas las peticiones pasan por Nginx usando el prefijo /api.
      - VITE_BACKEND_URL=/api
  
  todo-backend:
    image: todo-backend-dev
    volumes:
      - ./todo-backend:/usr/src/app
    environment:
      - MONGO_URL=mongodb://the_username:the_password@mongo:27017/the_database
      - REDIS_URL=redis://redis:6379
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - mongo_data:/data/db

  redis:
    image: redis
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - ./todo-backend/redis_data:/data
  
  nginx:
    image: nginx:1.25-alpine
    # Único punto de entrada desde el navegador.
    ports:
      - 8080:80
    volumes:
      # Configuración de Nginx en modo solo lectura (:ro).
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - todo-frontend
      - todo-backend
  
  debug-helper:
    image: busybox

volumes:
  mongo_data: