# "services" define los contenedores.
services:
  # Nombre del servicio.
  todo-backend: 
    # Nombre que tendr√° la imagen generada.
    image: todo-backend
    # Busca el Dockerfile en la carpeta actual.
    build: .
    ports:
      - 3000:3000
